_wandb:
    value:
        cli_version: 0.19.8
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 9
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 103
                - 105
            "2":
                - 1
                - 2
                - 3
                - 5
                - 9
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 103
                - 105
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.11.11
            "5": 0.19.8
            "6": 4.49.0
            "8":
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
